---
title: "BIS 015L AttrAlcoholDeaths"
output: html_document
date: "2025-02-25"
---

```{r}
library(tidyverse)
library(naniar)
library(janitor)
#install.packages("readxl")
library(readxl)
```

```{r}
alcoholattrdeaths <- read_excel("C:/Users/bryan/OneDrive/Desktop/BIS 015L Project/AlcoholAttrDeaths.xlsx") %>% clean_names()
```

```{r}
harmful_effects_summary <- alcoholattrdeaths %>% 
  slice(5:8) %>% 
  rename(harmful_effects_summary = annual_average_for_california_2020_2021,
        overall = x2,
         males = x3,
         females = x4) %>% 
  slice(2:4)
```

```{r}
harmful_effects_chronic <- alcoholattrdeaths %>% #need to deal with headers like cancer, alcohol attributed, etc.
  slice(12:62) %>% 
  rename(harmful_effects_chronic = annual_average_for_california_2020_2021,
        overall = x2,
         males = x3,
         females = x4)
```

```{r}
harmful_effects_acute <- alcoholattrdeaths %>% 
  slice(64:90) %>% 
  rename(harmful_effects_acute = annual_average_for_california_2020_2021,
        overall = x2,
         males = x3,
         females = x4)
```

```{r}
beneficial_effects <- alcoholattrdeaths %>% 
  slice(94:100) %>% 
   rename(beneficial_effects = annual_average_for_california_2020_2021,
        overall = x2,
         males = x3,
         females = x4)
```


